### ISSUE TITLE
database dir

### ISSUE THREAD

**Issue by roughnecks** [nicholaswilde/docker-chyrp-lite#73]
Hello,
asking for a friend who's setting this up: what directory path must we use for db setup?

we're getting this error:

![zb2rhnwCMfJowCXcci1YBVog22hiXjjNuCUpsAJ5onLVaDn1s](https://github.com/nicholaswilde/docker-chyrp-lite/assets/1666536/e4a9095e-521f-49cc-ae66-abf2b3711b8d)

Thanks

**Comment by roughnecks** [comment]
@nicholaswilde Can you help?

**Comment by shukebeta** [comment]
@roughnecks using `/data/data.db` should be ok if you are using the docker-compose.yml file.

**Comment by roughnecks** [comment]
Thanks
